name: Arduino Code Auto Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        mkdir -p ~/Arduino
        echo 'export PATH="$HOME/bin:$PATH"' >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli lib install "Adafruit GFX Library" "Adafruit SSD1306"

    - name: Compile Sketch
      run: arduino-cli compile --fqbn arduino:avr:uno path/to/your/sketch

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automated commit by GitHub Actions"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
