name: Weekly Summary

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Weekly Summary
      run: |
        echo "## Weekly Summary" > SUMMARY.md
        echo "### Commits" >> SUMMARY.md
        git log --oneline --since="1 week ago" >> SUMMARY.md
        echo "### Issues" >> SUMMARY.md
        gh issue list --state all --json title,createdAt --jq '.[] | "\(.title) - \(.createdAt)"' >> SUMMARY.md
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Actions"
        git add SUMMARY.md
        git commit -m "Update weekly summary"
        git push
